diff -Naur onvif_simple_server.ori/Makefile.static onvif_simple_server/Makefile.static
--- onvif_simple_server.ori/Makefile.static	2025-10-01 17:37:03.255839643 +0200
+++ onvif_simple_server/Makefile.static	2025-10-01 17:32:55.490742999 +0200
@@ -29,6 +29,11 @@
     STRIP=echo
 endif
 
+INCLUDE += -std=gnu99
+LIBS_O += -lm
+LIBS_N += -lm
+LIBS_W += -lm
+
 all: onvif_simple_server onvif_notify_server wsd_simple_server
 
 log.o: log.c $(HEADERS)
